version: '2'
services:
    businesshourscalculator-sonar:
        container_name: businesshourscalculator-sonar
        image: sonarqube:5.5-alpine
        ports:
            - 9000:9000
            - 9092:9092
